version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - '.:/app'
    networks:
      - stacknet
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    networks:
      - stacknet
    volumes:
      - 'nestpostgres:/var/lib/postgresql/data'
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    restart: always
    networks:
      - stacknet
    ports:
      - '8080:80'
    volumes:
      - 'nestpostgres:/var/lib/postgresql/data'
    env_file:
      - docker.env

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - stacknet

networks:
  stacknet:
    driver: bridge
volumes:
  nestpostgres:
    driver: local
