version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    networks:
      - stacknet
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:15.1
    restart: always
    ports:
      - '${FORWARD_POSTGRES_PORT:-5432}:5432'
    networks:
      - stacknet
    volumes:
      - 'pgdatabase:/var/lib/postgresql/data'
    environment:
      #- POSTGRES_USER='${POSTGRES_USER:-postgres}' // Default user is postgress
      - POSTGRES_PASSWORD='${POSTGRES_PASSWORD:-password}'
      #- POSTGRES_DB='${POSTGRES_DB:-postgres}' // There is a default db postgress
  pgadmin:
    image: dpage/pgadmin4:6.18
    restart: always
    networks:
      - stacknet
    ports:
      - '8080:80'
    volumes:
      - 'pgdatabase:/var/lib/postgresql/data'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password

  #mailhog:
  #image: 'mailhog/mailhog:latest'
  #ports:
  #- '${FORWARD_MAILHOG_PORT:-1025}:1025'
  #- '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
  #networks:
  #- stacknet

networks:
  stacknet:
    driver: bridge
volumes:
  pgdatabase:
    driver: local
